image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp dist/*.html public/
    - cp -r dist/js public/js
    - cp -r dist/css public/css
    - cp -r dist/images public/images
  artifacts:
    paths:
      - public
  only:
    - main
